#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: configure_ac
# autospec version: v22
# autospec commit: 247c192
#
Name     : rasdaemon
Version  : 0.8.3
Release  : 2
URL      : https://github.com/mchehab/rasdaemon/archive/refs/tags/v0.8.3.tar.gz
Source0  : https://github.com/mchehab/rasdaemon/archive/refs/tags/v0.8.3.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0
Requires: rasdaemon-bin = %{version}-%{release}
Requires: rasdaemon-license = %{version}-%{release}
Requires: rasdaemon-man = %{version}-%{release}
BuildRequires : file
BuildRequires : pkgconfig(libtraceevent)
BuildRequires : sqlite-autoconf-dev
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
RAS Daemon
==========
Those tools provide a way to get Platform Reliability, Availability
and Serviceability (RAS) reports made via the Kernel tracing events.

%package bin
Summary: bin components for the rasdaemon package.
Group: Binaries
Requires: rasdaemon-license = %{version}-%{release}

%description bin
bin components for the rasdaemon package.


%package dev
Summary: dev components for the rasdaemon package.
Group: Development
Requires: rasdaemon-bin = %{version}-%{release}
Provides: rasdaemon-devel = %{version}-%{release}
Requires: rasdaemon = %{version}-%{release}

%description dev
dev components for the rasdaemon package.


%package license
Summary: license components for the rasdaemon package.
Group: Default

%description license
license components for the rasdaemon package.


%package man
Summary: man components for the rasdaemon package.
Group: Default

%description man
man components for the rasdaemon package.


%prep
%setup -q -n rasdaemon-0.8.3
cd %{_builddir}/rasdaemon-0.8.3

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1743525082
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
%reconfigure --disable-static --enable-sqlite3 \
--enable-aer \
--enable-mce \
--enable-extlog \
--enable-devlink \
--enable-diskerror \
--enable-memory-failure \
--enable-cpu-fault-isolation
make  %{?_smp_mflags}

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make %{?_smp_mflags} check

%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export SOURCE_DATE_EPOCH=1743525082
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/rasdaemon
cp %{_builddir}/rasdaemon-%{version}/COPYING %{buildroot}/usr/share/package-licenses/rasdaemon/62681cf0443adb29fe101c7a4993deda818b2c40 || :
export GOAMD64=v2
GOAMD64=v2
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/ras-mc-ctl
/usr/bin/rasdaemon

%files dev
%defattr(-,root,root,-)
/usr/include/bitfield.h
/usr/include/config.h
/usr/include/non-standard-ampere.h
/usr/include/non-standard-hisilicon.h
/usr/include/non-standard-jaguarmicro.h
/usr/include/non-standard-yitian.h
/usr/include/queue.h
/usr/include/ras-aer-handler.h
/usr/include/ras-arm-handler.h
/usr/include/ras-cpu-isolation.h
/usr/include/ras-cxl-handler.h
/usr/include/ras-devlink-handler.h
/usr/include/ras-diskerror-handler.h
/usr/include/ras-events.h
/usr/include/ras-extlog-handler.h
/usr/include/ras-logger.h
/usr/include/ras-mc-handler.h
/usr/include/ras-mce-handler.h
/usr/include/ras-memory-failure-handler.h
/usr/include/ras-non-standard-handler.h
/usr/include/ras-page-isolation.h
/usr/include/ras-record.h
/usr/include/ras-report.h
/usr/include/rbtree.h
/usr/include/trigger.h
/usr/include/types.h
/usr/include/unified-sel.h

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/rasdaemon/62681cf0443adb29fe101c7a4993deda818b2c40

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/rasdaemon.1
/usr/share/man/man8/ras-mc-ctl.8
